#ifndef UC2_GLOBAL_H_INCLUDED
#define UC2_GLOBAL_H_INCLUDED

#define GLOBAL_UC2_SYS_UART0_BITRATE     115200
#define GLOBAL_UC2_SYS_UART1_BITRATE     115200
#define GLOBAL_UC2_SYS_UART0_RECBUFSIZE  16

#endif // UC2_GLOBAL_H_INCLUDED
