#ifndef UC1_GLOBAL_H_INCLUDED
#define UC1_GLOBAL_H_INCLUDED

#define GLOBAL_UC1_SYS_UART0_BITRATE     115200
#define GLOBAL_UC1_SYS_UART1_BITRATE     19200
#define GLOBAL_UC1_SYS_UART0_RECBUFSIZE  16

#endif // UC1_GLOBAL_H_INCLUDED
